
server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/restaurant
    username: MySql
    password: MySql48!

  jpa:
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
