server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/restaurant
    username: MySql
    password: MySql48!

  jpa:
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #    hibernate:
  #      ddl-auto: update

#  security:
#    oauth2:
      #      resource:
      #       tokenInfoUri:
#      client:
#        registration:
#          google:
#            client-id: 637154686366-903orc4fh92kqksnso6h9qgkv01eu62j.apps.googleusercontent.com
#            client-secret: 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
#            clientName: google
#            redirect-uri: http://localhost:8084/login/oauth2/code/google
#            code=EAR76A
#            authorization-grant-type: authorization_code
#            scope: read, write
#        provider:
#         okta:
#                  authorization-uri: https://dev-1234.oktapreview.com/oauth2/v1/authorize
#                  token-uri: https://dev-1234.googl.com/oauth2/v1/token

      resourceserver:
        jwt:
          public-key-location:
  cache:
    type: redis
  redis:
    port: 6379
    host: localhost

rabbitmq:
  image: rabbitmq:management
  ports: 15672

#  grant_type=authorization_code
#  &code=xxxxxxxxxxx
#  &redirect_uri=https://example-app.com/redirect
#  &code_verifier=Th7UHJdLswIYQxwSg29DbK1a_d9o41uNMTRmuH0PM8zyoMAQ
#  &client_id=xxxxxxxxxx
#  &client_secret=xxxxxxxxxx


auth:
  secret: token1
  header: authHead


